### ISSUE TITLE
Figure out "freezing" issue in Windows 10

### ISSUE THREAD

**Issue by gamozolabs** [gamozolabs/applepie#3]
Booting Windows 10 results in a "freeze" where everything seemingly locks up. Not sure what this is. Probably because we removed device ticking during emulation?

**Comment by gamozolabs** [comment]
Seems to happen to FreeBSD as well? Not sure if it's a freeze or just an extremely expensive I/O option.

Maybe the VGA is not being redrawn too? It could still be live.

**Comment by gamozolabs** [comment]
Spectre/meltdown mitigations causing massive cr3 changes?

**Comment by woachk** [comment]
WHVP has bugs that make it unable to boot real-world 32-bit OSes for now. SMP emulation is also broken.
Also, enabling the Hyper-V feature isn't the requirement, enabling the "Windows Hypervisor Platform" one is. :)

**Comment by woachk** [comment]
@gamozolabs check if they were MMIO instructions, and if so you might have to set exit_ctx.ExitReason = WHvRunVpExitReasonMemoryAccess; manually.

**Comment by gamozolabs** [comment]
Hmm? How does that work? Is WHVP setting a different return code for MMIO accesses incorrectly?

**Comment by woachk** [comment]
yep, and it can return WHvRunVpExitReasonCanceled in such cases, you'll have to really confirm that they're MMIO afterwards

**Comment by gamozolabs** [comment]
Fixed.

If a VM exit occurred where the next instruction to execute straddles a page boundary, RIP was updated internally and then restored to BX_CPU_THIS_PTR prev_rip. Meaning in this rare case RIP would be clobbered with a stale value. (See `BX_CPU_C::boundaryFetch()`) where "// Restore EIP since we fudged it to start at the 2nd page boundary."
